<?php
declare(strict_types=1);
$root=dirname(__DIR__);$errors=[];
$required=['database/migrate_phase39_0.sql','app/services/FleetInspectionService.php','app/services/InspectionDueService.php','app/controllers/InspectionController.php','app/controllers/InspectionDefectController.php','app/controllers/InspectionScheduleController.php','app/controllers/InspectionTemplateController.php','app/views/portal/inspections/index.php','app/views/portal/inspections/show.php','app/views/portal/inspection-defects/index.php','app/views/portal/mobile/inspect-asset.php','scripts/inspection-due.php','database/demo/seed_fleetwarden_m4_brighthaven.sql'];foreach($required as $f){if(!is_file($root.'/'.$f))$errors[]='Missing '.$f;}
$m=@file_get_contents($root.'/database/migrate_phase39_0.sql')?:'';foreach(['inspection_schedules','inspection_defects','inspection_worker_runs','asset_id','inspection_schedule_id','overall_severity','corrective_work_order_id','out_of_service_on_fail','requires_photo_on_fail','inspection.resolve','inspection.schedule'] as $n){if(!str_contains($m,$n))$errors[]='Migration missing '.$n;}
if(preg_match('/ALTER\s+TABLE[^;]*ADD\s+COLUMN\s+IF\s+NOT\s+EXISTS/i',$m))$errors[]='Unsupported ADD COLUMN IF NOT EXISTS syntax returned';
if(str_contains($m,'CHECK ('))$errors[]='Milestone 4 migration unexpectedly introduces CHECK/FK referential-action compatibility risk';
$r=@file_get_contents($root.'/public/index.php')?:'';foreach(['/portal/inspections','/portal/inspection-templates','/portal/inspection-defects','/portal/mobile/inspections/{id}','InspectionScheduleController::class'] as $n){if(!str_contains($r,$n))$errors[]='Router missing '.$n;}
$s=@file_get_contents($root.'/app/services/FleetInspectionService.php')?:'';foreach(['inspection.failed','inspection.out_of_service','createCorrectiveWorkOrder','resolveDefect','setAssetOutOfService','inspection_defects'] as $n){if(!str_contains($s,$n))$errors[]='Inspection service missing '.$n;}
$worker=@file_get_contents($root.'/scripts/inspection-due.php')?:'';if(!str_contains($worker,'flock'))$errors[]='Inspection worker lacks concurrency lock';
$sidebar=@file_get_contents($root.'/app/views/partials/portal-sidebar.php')?:'';foreach(["'/portal/inspections'","'/portal/inspection-templates'","'/portal/inspection-defects'"] as $n){if(!str_contains($sidebar,$n))$errors[]='Inspection navigation missing '.$n;}
$packet=@file_get_contents($root.'/app/views/pdf/inspection-packet.php')?:'';if(str_contains($packet,'Rock Bluffs'))$errors[]='Legacy Rock Bluffs branding remains in inspection PDF';if(!str_contains($packet,'FleetWarden'))$errors[]='FleetWarden inspection packet branding missing';
if($errors){fwrite(STDERR,"FleetWarden Milestone 4 regression failed:\n- ".implode("\n- ",$errors)."\n");exit(1);}echo "FleetWarden Milestone 4 regression passed.\n";
